application: disena-un-landing
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /styles(.*\.(css|js|gif|png|jpg|ico|js|php|xml|svg|ttf|woff|gif|jpeg))
  static_files: styles\1
  upload: styles(.*\.(css|js|gif|png|jpg|ico|js|php|xml|svg|ttf|woff|gif))

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
